# Generated by Django 4.1.2 on 2024-06-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['rut']},
        ),
    ]
